{{- if and (not .Values.existingSecret) .Values.config.auth.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "driftwire.fullname" . }}-secret
  labels:
    {{- include "driftwire.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.auth.jwtSecret | b64enc | quote }}
{{- end }}
