version: '2'

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused constants, variables, functions
    - misspell      # Check for misspelled English words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - unparam       # Check for unused function parameters

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow      # Too strict for practical use

  staticcheck:
    checks: ["all"]

  gosec:
    excludes:
      - G104  # Allow unchecked errors in some cases
      - G307  # Allow deferred file.Close() without checking error

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude testutil mock files
    - path: pkg/testutil/
      linters:
        - errcheck
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
