run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check if code is formatted
    - goimports     # Check if imports are formatted
    - misspell      # Check for misspelled English words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - gocritic      # Highly extensible Go linter
    - unparam       # Check for unused function parameters

  disable:
    - typecheck     # Can cause issues with generics

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow      # Too strict for practical use

  staticcheck:
    checks: ["all"]

  gosec:
    excludes:
      - G104  # Allow unchecked errors in some cases
      - G307  # Allow deferred file.Close() without checking error

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentedOutCode
      - deprecatedComment
      - dupImport
      - emptyStringTest
      - hexLiteral
      - nilValReturn
      - rangeValCopy
      - singleCaseSwitch
      - switchTrue
      - typeAssertChain
      - unlambda
      - unslice

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Exclude testutil mock files
    - path: pkg/testutil/
      linters:
        - errcheck
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
