#!/bin/bash
set -e

# TFDrift-Falco Quick Start Setup
# Prepares everything `docker compose up -d` needs on a fresh clone:
# config.yaml, .env, and self-signed TLS certs for Falco gRPC.
#
# Usage:
#   ./quick-start.sh          # interactive
#   ./quick-start.sh --yes    # non-interactive, sensible defaults

VERSION="$(tr -d '[:space:]' < VERSION 2>/dev/null || echo dev)"
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

NONINTERACTIVE=0
[ "${1:-}" = "--yes" ] || [ "${1:-}" = "-y" ] && NONINTERACTIVE=1

echo -e "${BOLD}🚀 TFDrift-Falco Quick Start (v${VERSION})${NC}"
echo ""
echo "This script will set up TFDrift-Falco with Falco in Docker."
echo ""

# Check prerequisites
echo -e "${BOLD}📋 Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed${NC}"
    echo "Please install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "${GREEN}✅ Docker installed${NC}"

if ! docker compose version &> /dev/null; then
    echo -e "${RED}❌ Docker Compose is not installed${NC}"
    echo "Please install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi
echo -e "${GREEN}✅ Docker Compose installed${NC}"

if ! command -v openssl &> /dev/null; then
    echo -e "${RED}❌ openssl is not installed (needed to generate Falco gRPC certs)${NC}"
    exit 1
fi
echo -e "${GREEN}✅ openssl installed${NC}"

# AWS credentials: only needed for live CloudTrail/S3 access. The default
# compose stack (falco-simple.yaml) boots without them, so warn instead of
# blocking.
if [ ! -f "${HOME}/.aws/credentials" ]; then
    echo -e "${YELLOW}⚠️  No AWS credentials at ~/.aws/credentials — the stack will boot, but live AWS drift detection needs them (aws configure).${NC}"
else
    echo -e "${GREEN}✅ AWS credentials found${NC}"
fi

echo ""
echo -e "${BOLD}🔐 Falco gRPC TLS certificates...${NC}"
# docker-compose.yml mounts ./deployments/falco as /etc/falco/certs and
# falco-simple.yaml expects server.key / server.crt there. These are
# intentionally not committed (they are private keys) — generate per install.
if [ -f deployments/falco/server.key ] && [ -f deployments/falco/server.crt ]; then
    echo -e "${GREEN}✅ Existing certs found (deployments/falco/server.{key,crt})${NC}"
else
    openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes \
        -keyout deployments/falco/server.key \
        -out deployments/falco/server.crt \
        -subj "/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,DNS:falco,IP:127.0.0.1" 2>/dev/null
    echo -e "${GREEN}✅ Self-signed certs generated (CN=localhost, SAN: falco)${NC}"
fi

# NOTE: Falco config (deployments/falco/falco-simple.yaml) and drift rules
# (rules/terraform_drift.yaml) ship with the repository and are validated in
# CI — this script no longer generates or overwrites them.

# Prompt for configuration
echo ""
echo -e "${BOLD}🔧 TFDrift-Falco Configuration${NC}"
echo ""

if [ "$NONINTERACTIVE" = "1" ]; then
    aws_region="us-east-1"
    backend_choice="2"
    slack_webhook=""
    echo "(--yes: region=us-east-1, backend=local, no Slack)"
else
    read -p "AWS Region to monitor (default: us-east-1): " aws_region
    aws_region=${aws_region:-us-east-1}

    echo ""
    echo "Terraform State Backend:"
    echo "  1) S3 (recommended for production)"
    echo "  2) Local file (for testing)"
    read -p "Select backend (1-2, default: 2): " backend_choice
    backend_choice=${backend_choice:-2}
fi

if [ "$backend_choice" == "1" ]; then
    read -p "S3 bucket name: " s3_bucket
    read -p "S3 key (e.g., prod/terraform.tfstate): " s3_key

    state_config=$(cat <<EOF
    state:
      backend: "s3"
      s3_bucket: "${s3_bucket}"
      s3_key: "${s3_key}"
EOF
    )
else
    # Create example Terraform state
    mkdir -p examples/terraform
    if [ ! -f examples/terraform/terraform.tfstate ]; then
        echo '{"version": 4, "terraform_version": "1.0.0", "resources": []}' > examples/terraform/terraform.tfstate
    fi

    state_config=$(cat <<EOF
    state:
      backend: "local"
      local_path: "/terraform/terraform.tfstate"
EOF
    )
fi

# Slack Webhook (optional)
if [ "$NONINTERACTIVE" != "1" ]; then
    echo ""
    read -p "Slack webhook URL (optional, press Enter to skip): " slack_webhook
fi

if [ -n "$slack_webhook" ]; then
    slack_config=$(cat <<EOF
  slack:
    enabled: true
    webhook_url: "${slack_webhook}"
    channel: "#tfdrift-alerts"
EOF
    )
else
    slack_config=$(cat <<EOF
  slack:
    enabled: false
EOF
    )
fi

# Create TFDrift-Falco configuration
echo ""
echo -e "${YELLOW}Creating TFDrift-Falco configuration...${NC}"
cat > config.yaml <<EOF
# TFDrift-Falco Configuration (Auto-generated by quick-start.sh)

# Cloud Provider Configuration
providers:
  aws:
    enabled: true
    regions:
      - ${aws_region}
${state_config}

# Falco Integration
falco:
  enabled: true
  hostname: "falco"
  port: 5060

# Drift Detection Rules
drift_rules:
  - name: "EC2 Instance Modification"
    resource_types:
      - "aws_instance"
    watched_attributes:
      - "instance_type"
      - "disable_api_termination"
      - "security_groups"
    severity: "high"

  - name: "Security Group Changes"
    resource_types:
      - "aws_security_group"
      - "aws_security_group_rule"
    watched_attributes:
      - "ingress"
      - "egress"
      - "cidr_blocks"
    severity: "critical"

  - name: "IAM Policy Changes"
    resource_types:
      - "aws_iam_role"
      - "aws_iam_policy"
      - "aws_iam_user"
    watched_attributes:
      - "policy"
      - "assume_role_policy"
      - "inline_policy"
    severity: "critical"

  - name: "S3 Bucket Security"
    resource_types:
      - "aws_s3_bucket"
      - "aws_s3_bucket_public_access_block"
    watched_attributes:
      - "block_public_acls"
      - "block_public_policy"
      - "ignore_public_acls"
      - "restrict_public_buckets"
    severity: "critical"

# Notification Channels
notifications:
${slack_config}

  falco_output:
    enabled: true
    priority: "warning"

# Logging
logging:
  level: "info"
  format: "json"
EOF

echo -e "${GREEN}✅ TFDrift-Falco configuration created${NC}"

# Create .env file
echo ""
echo -e "${YELLOW}Creating .env file...${NC}"
cat > .env <<EOF
# TFDrift-Falco Environment Variables
AWS_REGION=${aws_region}
TZ=UTC
EOF

echo -e "${GREEN}✅ .env file created${NC}"

# Summary
echo ""
echo -e "${BOLD}${GREEN}✅ Setup Complete!${NC}"
echo ""
echo -e "${BOLD}🚀 Start TFDrift-Falco:${NC}"
echo ""
echo -e "  ${BOLD}docker compose up -d${NC}"
echo ""
echo -e "${BOLD}📊 View logs:${NC}"
echo ""
echo "  docker compose logs -f tfdrift"
echo "  docker compose logs -f falco"
echo ""
echo -e "${BOLD}🛑 Stop services:${NC}"
echo ""
echo "  docker compose down"
echo ""
echo -e "${BOLD}📚 Next Steps:${NC}"
echo ""
echo "  1. Review configuration: vim config.yaml"
echo "  2. Customize drift rules for your infrastructure"
echo "  3. Set up Slack/webhook notifications"
echo "  4. Read full documentation: https://github.com/higakikeita/tfdrift-falco"
echo ""
echo -e "${YELLOW}⚡ Pro tip: Run 'make logs' or 'make restart' for common operations${NC}"
echo ""
